# Generated by Django 3.0.4 on 2020-03-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя Поезда')),
                ('travel_time', models.IntegerField(verbose_name='Время в пути')),
                ('city_of_arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_of_arrival', to='cities.City', verbose_name='Город прибытия')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city', to='cities.City', verbose_name='Город отправления')),
            ],
            options={
                'verbose_name': 'Поезд',
                'verbose_name_plural': 'Поезда',
                'ordering': ['name'],
            },
        ),
    ]
